[build]
  # اترك الـ base فارغاً لأن package.json في الجذر
  base = ""
  
  # تأكد من تثبيت الحزم ثم البناء
  command = "npm install && npm run build"
  
  # المسار النهائي الذي سيحتوي على ملفات index.html
  publish = "client/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200