[build]
  base = "/"
  command = "npm install && npm run build"
  # هنا نبحث عن المجلد الذي سينتجه Vite بناءً على الإعدادات أعلاه
  publish = "client/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200